-- ===================================================
--  ============= 4.0) Product Analysis =============
-- ===================================================

-- 4.0) PRODUCT ANALYSIS NOTE:
-- All revenue in this section is calculated using Net Product Price (Excluding Tax).
-- This ensures that product performance metrics are not skewed by tax variations.

-- 4.1.1) exploring the products
SELECT * FROM products;

-- 4.1.2) exploring the type of products we sell
SELECT * FROM product_type;

-- 4.1.3) exploring the brands we sell
SELECT * FROM product_brand;

-- 4.1.4) Overall Checking the types of product, product_type and brand we sell
SELECT 
       p.product_id, p.product_name, 
       pt.product_type_id, pt.product_type_name, 
       pb.brand_id, pb.brand_name
FROM products as p
INNER JOIN product_type as pt
ON p.product_id=pt.product_id
INNER JOIN product_brand as pb
ON p.product_id=pb.product_id;

-- COUNT OF all the types of products we sell=201
SELECT COUNT(*) AS COUNT_All_Types_of_Products_we_Sell
FROM products as p
INNER JOIN product_type as pt
ON p.product_id=pt.product_id
INNER JOIN product_brand as pb
ON p.product_id=pb.product_id;

-- 4.2.1) Revenue By each product we sell 
SELECT 
	  ii.product_id, pd.product_name, 
      SUM(ii.final_product_price) 
      AS Revenue_Each_Product
FROM invoice_items as ii
INNER JOIN products as pd
ON ii.product_id=pd.product_id
GROUP BY ii.product_id, pd.product_name
ORDER BY Revenue_Each_Product DESC;

-- verifying the query  45185294.00
SELECT SUM(ii.final_product_price) FROM invoice_items as ii;

-- 4.2.2) Quantity of Products Solds and Revenue generated by each Product

SELECT ii.product_id, pd.product_name, 
       SUM(ii.quantity) AS Quantity_Sold,
       SUM(ii.final_product_price) AS Revenue
FROM invoice_items as ii
INNER JOIN products as pd
ON pd.product_id=ii.product_id
GROUP BY ii.product_id, pd.product_name 
ORDER BY Quantity_Sold DESC;

-- OR

WITH products AS (
SELECT p.product_id, p.product_name
FROM products as p
)
SELECT ii.product_id, p.product_name, SUM(ii.quantity) AS Quantity_Sold
FROM invoice_items as ii
INNER JOIN products as p
ON p.product_id=ii.product_id
GROUP BY ii.product_id, p.product_name 
ORDER BY Quantity_Sold DESC;

-- 4.2.3) Products V/S Customer_Type   

WITH products AS (
SELECT p.product_id, p.product_name
FROM products as p
)
SELECT ii.product_id, pd.product_name,
	   SUM( CASE WHEN customer_type="New" THEN ii.quantity ELSE 0 END) AS New,
       SUM( CASE WHEN customer_type="Referral" THEN ii.quantity ELSE 0 END) AS Referral
FROM invoice_items as ii
INNER JOIN invoices as i
ON ii.invoice_id=i.invoice_id
INNER JOIN customers_details as c
ON c.customer_id=i.customer_id
INNER JOIN products as pd
ON pd.product_id=ii.product_id
GROUP BY ii.product_id, pd.product_name;

-- verifying the query
SELECT SUM(ii.quantity) AS Total_Quantities_Sold FROM invoice_items as ii;
 
-- 4.2.4) Revenue Comparison with Tax and without Tax

-- Revenue_without_Tax = 45185294.00
SELECT SUM(final_product_price) AS Revenue_without_Tax FROM invoice_items;

-- Revenue_with_Tax = 46811413.00
SELECT SUM(final_bill_amount) AS Revenue_with_Tax FROM invoices;

-- Amount_Tax_Collected = 1626119 Tax Collected from the 
SELECT (ROUND( (SELECT SUM(final_bill_amount) FROM invoices) - (SELECT SUM(final_product_price) FROM invoice_items))) AS Tax_Collected;

-- 4.2.5) Revenue Collected from each brand
SELECT 
      pb.brand_id, pb.brand_name, 
      SUM(ii.final_product_price) 
      AS Revenue_Collected_Brand
FROM product_brand as pb
INNER JOIN invoice_items as ii
ON pb.brand_id=ii.brand_id
GROUP BY pb.brand_id, pb.brand_name
ORDER BY Revenue_Collected_Brand DESC;

-- 4.2.6) Revenue by each type of product 
SELECT pt.product_id, pd.product_name, ii.product_type_id, pt.product_type_name, SUM(ii.final_product_price) AS Revenue_each_product_type
FROM invoice_items as ii
INNER JOIN products as pd
ON pd.product_id=ii.product_id
INNER JOIN product_type as pt
ON ii.product_type_id=pt.product_type_id
GROUP BY pt.product_id, pd.product_name, ii.product_type_id, pt.product_type_name 
ORDER BY ii.product_type_id DESC;

-- 4.2.7) Revenue by each product brand 

WITH product_name_brand_name AS (
SELECT pd.product_id, pd.product_name, pb.brand_id, pb.brand_name
FROM products as pd
INNER JOIN product_brand as pb
ON pd.product_id=pb.product_id
)
SELECT pnbn.product_id, pnbn.product_name, pnbn.brand_id, pnbn.brand_name, SUM(ii.final_product_price) AS Revenue_Brand
FROM product_name_brand_name as pnbn
INNER JOIN invoice_items as ii
ON pnbn.brand_id=ii.brand_id
GROUP BY pnbn.product_id, pnbn.product_name, pnbn.brand_id, pnbn.brand_name 
ORDER BY Revenue_Brand DESC;

-- 4.2.8) Products + Customer_Age V/S Quantity of Products Sold
WITH unique_customers AS (
SELECT DISTINCT c.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.customer_id=i.customer_id
),
customer_age AS (
SELECT uc.customer_id, c.age
FROM unique_customers as uc
INNER JOIN customers_details as c
ON c.customer_id=uc.customer_id
),
customer_age_invoice AS (
SELECT ca.customer_id, ca.age, i.invoice_id
FROM customer_age as ca
INNER JOIN invoices as i
ON ca.customer_id=i.customer_id
),
customer_age_invoice_items AS (
SELECT cai.customer_id, cai.age, cai.invoice_id, ii.item_id, ii.product_id, ii.product_type_id, ii.brand_id, ii.final_product_price
FROM customer_age_invoice AS cai
INNER JOIN invoice_items as ii
ON cai.invoice_id=ii.invoice_id
)
SELECT 
CASE
    WHEN caii.age < 20 THEN "Teenage_Customer"
    WHEN caii.age BETWEEN 20 AND 30 THEN "20's Customer"
    WHEN caii.age BETWEEN 31 AND 40 THEN "30's Customer"
    WHEN caii.age BETWEEN 41 AND 50 THEN "40's Customer"
    WHEN caii.age BETWEEN 51 AND 60 THEN "50's Customer"
    WHEN caii.age > 60 THEN "Old_Age Customers"
  END AS Age_group,
SUM(CASE WHEN caii.product_id=1 THEN 1 END) AS QTY_Frames_SOLD,
SUM(CASE WHEN caii.product_id=2 THEN 1 END) AS QTY_Glass_SOLD,
SUM(CASE WHEN caii.product_id=3 THEN 1 END) AS QTY_Sunglass_SOLD,
SUM(CASE WHEN caii.product_id=4 THEN 1 END) AS QTY_Contact_Lens_SOLD,
SUM(CASE WHEN caii.product_id=6 THEN 1 END) AS QTY_Lens_SolutionS_SOLD,
SUM(CASE WHEN caii.product_id=5 THEN 1 END) AS QTY_Acessories_SOLD
FROM customer_age_invoice_items AS caii  
GROUP BY Age_group WITH ROLLUP;

-- Repeated Customers V/S Products

WITH unique_customers_from_invoices AS (
SELECT DISTINCT i.customer_id FROM invoices as i
),
repeated_customers AS (
SELECT DISTINCT rc.customer_id 
FROM repeated_customers as rc
INNER JOIN unique_customers_from_invoices as ucfi
ON rc.customer_id=ucfi.customer_id
),
repeated_customers_invoices AS (
SELECT rc.customer_id, i.invoice_id 
FROM repeated_customers as rc
INNER JOIN invoices as i
ON rc.customer_id=i.customer_id
),
repeated_customers_invoices_items AS (
SELECT rci.customer_id, rci.invoice_id, ii.item_id, ii.product_id, ii.brand_id, ii.product_type_id
FROM repeated_customers_invoices as rci
INNER JOIN invoice_items as ii
ON rci.invoice_id=ii.invoice_id
)
SELECT rcii.product_id, COUNT(rcii.customer_id)
FROM repeated_customers_invoices_items as rcii
GROUP BY rcii.product_id WITH ROLLUP
ORDER BY COUNT(rcii.customer_id) DESC;

-- Deep Product Analysis 
-- Product Summary across Buyer, Repeated, Churn Customers

WITH customers AS (
SELECT DISTINCT customer_id
FROM customers_details 
),
customers_detail AS (
SELECT 
       c.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id
FROM customers as c
INNER JOIN customers_details as cd
ON cd.customer_id=c.customer_id
),
cd_vision AS (
SELECT 
	   cd.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id,
       p.vision_type
FROM customers_detail as cd
INNER JOIN prescriptions as p
ON p.customer_id=cd.customer_id
),
cdv_staff AS (
SELECT 
       cdv.customer_id, cdv.age, cdv.mobile, cdv.customer_type,
       cdv.assigned_staff_id, cdv.referred_by_id,
       cdv.vision_type, s.staff_full_name
FROM cd_vision as cdv
INNER JOIN staff as s
ON s.staff_id=cdv.assigned_staff_id
),
cdvs_repeated AS (
SELECT 
       cdvs.customer_id, cdvs.age, cdvs.mobile, cdvs.customer_type,
       cdvs.assigned_staff_id, cdvs.referred_by_id,
       cdvs.vision_type, cdvs.staff_full_name,
	   rc.customer_id as repeated_customers
FROM cdv_staff as cdvs
LEFT JOIN repeated_customers as rc
ON rc.customer_id=cdvs.customer_id
),
cdvsr_churn AS (
SELECT 
       cdvsr.customer_id, cdvsr.age, cdvsr.mobile, cdvsr.customer_type,
       cdvsr.assigned_staff_id, cdvsr.referred_by_id,
       cdvsr.vision_type, cdvsr.staff_full_name,
	   cdvsr.repeated_customers,
       rcc.customer_id as repeated_churn_customers
FROM cdvs_repeated as cdvsr
LEFT JOIN repeated_churn_customers as rcc
ON cdvsr.customer_id=rcc.customer_id
),
cdvsrc_top AS (
SELECT 
       cdvsrc.customer_id, cdvsrc.age, cdvsrc.mobile, cdvsrc.customer_type,
       cdvsrc.assigned_staff_id, cdvsrc.referred_by_id,
       cdvsrc.vision_type, cdvsrc.staff_full_name,
	   cdvsrc.repeated_customers,
       cdvsrc.repeated_churn_customers,
       tc.customer_id as top_50_customers
FROM cdvsr_churn as cdvsrc
LEFT JOIN top_50_customers as tc
ON tc.customer_id=cdvsrc.customer_id
),
cdvsrct_invoices AS (
SELECT 
	   cdvsrct.customer_id, cdvsrct.age, cdvsrct.mobile, cdvsrct.customer_type,
       cdvsrct.assigned_staff_id, cdvsrct.referred_by_id,
       cdvsrct.vision_type, cdvsrct.staff_full_name,
	   cdvsrct.repeated_customers,
       cdvsrct.repeated_churn_customers,
       cdvsrct.top_50_customers,
       i.invoice_id
FROM cdvsrc_top as cdvsrct 
INNER JOIN invoices as i
ON i.customer_id=cdvsrct.customer_id
),
cdvsrcti_invoice_items AS (
SELECT 
	   cdvsrcti.customer_id, cdvsrcti.age, cdvsrcti.mobile, cdvsrcti.customer_type,
       cdvsrcti.assigned_staff_id, cdvsrcti.referred_by_id,
       cdvsrcti.vision_type, cdvsrcti.staff_full_name,
	   cdvsrcti.repeated_customers,
       cdvsrcti.repeated_churn_customers,
       cdvsrcti.top_50_customers,
       cdvsrcti.invoice_id, ii.item_id, ii.product_id, ii.brand_id, ii.product_type_id,
       ii.quantity
FROM cdvsrct_invoices as cdvsrcti
INNER JOIN invoice_items as ii
ON ii.invoice_id=cdvsrcti.invoice_id
)
SELECT 
	  pd.product_name, 
      SUM(CASE WHEN cdvsrctiii.customer_id 
      AND cdvsrctiii.repeated_customers IS NULL 
      AND cdvsrctiii.repeated_churn_customers IS NULL THEN cdvsrctiii.quantity END) AS First_Time_Purchase_Quantity,
      SUM(CASE WHEN cdvsrctiii.repeated_customers
      AND cdvsrctiii.repeated_churn_customers IS NULL 
      THEN cdvsrctiii.quantity END) AS Active_Repeat_Purchase_Quantity,
      SUM(CASE WHEN cdvsrctiii.repeated_churn_customers THEN cdvsrctiii.quantity END) AS Churned_Repeat_Purchase_Quantity
FROM cdvsrcti_invoice_items as cdvsrctiii
INNER JOIN products as pd
ON pd.product_id=cdvsrctiii.product_id
GROUP BY pd.product_name WITH ROLLUP;


-- Summary of QTY SOLD across Buyers, Repeated and Churn Customers 
WITH customers AS (
SELECT DISTINCT customer_id
FROM customers_details 
),
customers_detail AS (
SELECT 
       c.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id
FROM customers as c
INNER JOIN customers_details as cd
ON cd.customer_id=c.customer_id
),
cd_vision AS (
SELECT 
	   cd.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id,
       p.vision_type
FROM customers_detail as cd
INNER JOIN prescriptions as p
ON p.customer_id=cd.customer_id
),
cdv_staff AS (
SELECT 
       cdv.customer_id, cdv.age, cdv.mobile, cdv.customer_type,
       cdv.assigned_staff_id, cdv.referred_by_id,
       cdv.vision_type, s.staff_full_name
FROM cd_vision as cdv
INNER JOIN staff as s
ON s.staff_id=cdv.assigned_staff_id
),
cdvs_repeated AS (
SELECT 
       cdvs.customer_id, cdvs.age, cdvs.mobile, cdvs.customer_type,
       cdvs.assigned_staff_id, cdvs.referred_by_id,
       cdvs.vision_type, cdvs.staff_full_name,
	   rc.customer_id as repeated_customers
FROM cdv_staff as cdvs
LEFT JOIN repeated_customers as rc
ON rc.customer_id=cdvs.customer_id
),
cdvsr_churn AS (
SELECT 
       cdvsr.customer_id, cdvsr.age, cdvsr.mobile, cdvsr.customer_type,
       cdvsr.assigned_staff_id, cdvsr.referred_by_id,
       cdvsr.vision_type, cdvsr.staff_full_name,
	   cdvsr.repeated_customers,
       rcc.customer_id as repeated_churn_customers
FROM cdvs_repeated as cdvsr
LEFT JOIN repeated_churn_customers as rcc
ON cdvsr.customer_id=rcc.customer_id
),
cdvsrc_top AS (
SELECT 
       cdvsrc.customer_id, cdvsrc.age, cdvsrc.mobile, cdvsrc.customer_type,
       cdvsrc.assigned_staff_id, cdvsrc.referred_by_id,
       cdvsrc.vision_type, cdvsrc.staff_full_name,
	   cdvsrc.repeated_customers,
       cdvsrc.repeated_churn_customers,
       tc.customer_id as top_50_customers
FROM cdvsr_churn as cdvsrc
LEFT JOIN top_50_customers as tc
ON tc.customer_id=cdvsrc.customer_id
),
cdvsrct_invoices AS (
SELECT 
	   cdvsrct.customer_id, cdvsrct.age, cdvsrct.mobile, cdvsrct.customer_type,
       cdvsrct.assigned_staff_id, cdvsrct.referred_by_id,
       cdvsrct.vision_type, cdvsrct.staff_full_name,
	   cdvsrct.repeated_customers,
       cdvsrct.repeated_churn_customers,
       cdvsrct.top_50_customers,
       i.invoice_id
FROM cdvsrc_top as cdvsrct 
INNER JOIN invoices as i
ON i.customer_id=cdvsrct.customer_id
),
cdvsrcti_invoice_items AS (
SELECT 
	   cdvsrcti.customer_id, cdvsrcti.age, cdvsrcti.mobile, cdvsrcti.customer_type,
       cdvsrcti.assigned_staff_id, cdvsrcti.referred_by_id,
       cdvsrcti.vision_type, cdvsrcti.staff_full_name,
	   cdvsrcti.repeated_customers,
       cdvsrcti.repeated_churn_customers,
       cdvsrcti.top_50_customers,
       cdvsrcti.invoice_id, ii.item_id, ii.product_id, ii.brand_id, ii.product_type_id,
       ii.quantity
FROM cdvsrct_invoices as cdvsrcti
INNER JOIN invoice_items as ii
ON ii.invoice_id=cdvsrcti.invoice_id
)
SELECT 
	  pd.product_name, 
      SUM(CASE WHEN cdvsrctiii.customer_id 
      AND cdvsrctiii.repeated_customers IS NULL 
      AND cdvsrctiii.repeated_churn_customers IS NULL THEN cdvsrctiii.quantity END) AS First_Time_Purchase_Quantity,
      SUM(CASE WHEN cdvsrctiii.repeated_customers
      AND cdvsrctiii.repeated_churn_customers IS NULL 
      THEN cdvsrctiii.quantity END) AS Active_Repeat_Purchase_Quantity,
      SUM(CASE WHEN cdvsrctiii.repeated_churn_customers THEN cdvsrctiii.quantity END) AS Churned_Repeat_Purchase_Quantity
FROM cdvsrcti_invoice_items as cdvsrctiii
INNER JOIN products as pd
ON pd.product_id=cdvsrctiii.product_id
GROUP BY pd.product_name WITH ROLLUP;

-- Summary of Products Sold Revenue across Buyers, Repeated and Churn 

WITH customers AS (
SELECT DISTINCT customer_id
FROM customers_details 
),
customers_detail AS (
SELECT 
       c.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id
FROM customers as c
INNER JOIN customers_details as cd
ON cd.customer_id=c.customer_id
),
cd_vision AS (
SELECT 
	   cd.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id,
       p.vision_type
FROM customers_detail as cd
INNER JOIN prescriptions as p
ON p.customer_id=cd.customer_id
),
cdv_staff AS (
SELECT 
       cdv.customer_id, cdv.age, cdv.mobile, cdv.customer_type,
       cdv.assigned_staff_id, cdv.referred_by_id,
       cdv.vision_type, s.staff_full_name
FROM cd_vision as cdv
INNER JOIN staff as s
ON s.staff_id=cdv.assigned_staff_id
),
cdvs_repeated AS (
SELECT 
       cdvs.customer_id, cdvs.age, cdvs.mobile, cdvs.customer_type,
       cdvs.assigned_staff_id, cdvs.referred_by_id,
       cdvs.vision_type, cdvs.staff_full_name,
	   rc.customer_id as repeated_customers
FROM cdv_staff as cdvs
LEFT JOIN repeated_customers as rc
ON rc.customer_id=cdvs.customer_id
),
cdvsr_churn AS (
SELECT 
       cdvsr.customer_id, cdvsr.age, cdvsr.mobile, cdvsr.customer_type,
       cdvsr.assigned_staff_id, cdvsr.referred_by_id,
       cdvsr.vision_type, cdvsr.staff_full_name,
	   cdvsr.repeated_customers,
       rcc.customer_id as repeated_churn_customers
FROM cdvs_repeated as cdvsr
LEFT JOIN repeated_churn_customers as rcc
ON cdvsr.customer_id=rcc.customer_id
),
cdvsrc_top AS (
SELECT 
       cdvsrc.customer_id, cdvsrc.age, cdvsrc.mobile, cdvsrc.customer_type,
       cdvsrc.assigned_staff_id, cdvsrc.referred_by_id,
       cdvsrc.vision_type, cdvsrc.staff_full_name,
	   cdvsrc.repeated_customers,
       cdvsrc.repeated_churn_customers,
       tc.customer_id as top_50_customers
FROM cdvsr_churn as cdvsrc
LEFT JOIN top_50_customers as tc
ON tc.customer_id=cdvsrc.customer_id
),
cdvsrct_invoices AS (
SELECT 
	   cdvsrct.customer_id, cdvsrct.age, cdvsrct.mobile, cdvsrct.customer_type,
       cdvsrct.assigned_staff_id, cdvsrct.referred_by_id,
       cdvsrct.vision_type, cdvsrct.staff_full_name,
	   cdvsrct.repeated_customers,
       cdvsrct.repeated_churn_customers,
       cdvsrct.top_50_customers,
       i.invoice_id
FROM cdvsrc_top as cdvsrct 
INNER JOIN invoices as i
ON i.customer_id=cdvsrct.customer_id
),
cdvsrcti_invoice_items AS (
SELECT 
	   cdvsrcti.customer_id, cdvsrcti.age, cdvsrcti.mobile, cdvsrcti.customer_type,
       cdvsrcti.assigned_staff_id, cdvsrcti.referred_by_id,
       cdvsrcti.vision_type, cdvsrcti.staff_full_name,
	   cdvsrcti.repeated_customers,
       cdvsrcti.repeated_churn_customers,
       cdvsrcti.top_50_customers, 
       cdvsrcti.invoice_id, ii.item_id, ii.product_id, ii.brand_id, ii.product_type_id,
       ii.quantity, ii.final_product_price
FROM cdvsrct_invoices as cdvsrcti
INNER JOIN invoice_items as ii
ON ii.invoice_id=cdvsrcti.invoice_id
)
SELECT 
	  pd.product_name, 
      SUM(CASE WHEN cdvsrctiii.customer_id 
      AND cdvsrctiii.repeated_customers IS NULL 
      AND cdvsrctiii.repeated_churn_customers IS NULL THEN cdvsrctiii.final_product_price END) AS First_Time_Purchase_Quantity,
      SUM(CASE WHEN cdvsrctiii.repeated_customers
      AND cdvsrctiii.repeated_churn_customers IS NULL 
      THEN cdvsrctiii.final_product_price END) AS Active_Repeat_Purchase_Quantity,
      SUM(CASE WHEN cdvsrctiii.repeated_churn_customers THEN cdvsrctiii.final_product_price END) AS Churned_Repeat_Purchase_Quantity
FROM cdvsrcti_invoice_items as cdvsrctiii
INNER JOIN products as pd
ON pd.product_id=cdvsrctiii.product_id
GROUP BY pd.product_name WITH ROLLUP;

-- Product_Summary Across Age group  

WITH customers AS (
SELECT DISTINCT customer_id
FROM customers_details 
),
customers_detail AS (
SELECT 
       c.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id
FROM customers as c
INNER JOIN customers_details as cd
ON cd.customer_id=c.customer_id
),
cd_vision AS (
SELECT 
	   cd.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id,
       p.vision_type
FROM customers_detail as cd
INNER JOIN prescriptions as p
ON p.customer_id=cd.customer_id
),
cdv_staff AS (
SELECT 
       cdv.customer_id, cdv.age, cdv.mobile, cdv.customer_type,
       cdv.assigned_staff_id, cdv.referred_by_id,
       cdv.vision_type, s.staff_full_name
FROM cd_vision as cdv
INNER JOIN staff as s
ON s.staff_id=cdv.assigned_staff_id
),
cdvs_repeated AS (
SELECT 
       cdvs.customer_id, cdvs.age, cdvs.mobile, cdvs.customer_type,
       cdvs.assigned_staff_id, cdvs.referred_by_id,
       cdvs.vision_type, cdvs.staff_full_name,
	   rc.customer_id as repeated_customers
FROM cdv_staff as cdvs
LEFT JOIN repeated_customers as rc
ON rc.customer_id=cdvs.customer_id
),
cdvsr_churn AS (
SELECT 
       cdvsr.customer_id, cdvsr.age, cdvsr.mobile, cdvsr.customer_type,
       cdvsr.assigned_staff_id, cdvsr.referred_by_id,
       cdvsr.vision_type, cdvsr.staff_full_name,
	   cdvsr.repeated_customers,
       rcc.customer_id as repeated_churn_customers
FROM cdvs_repeated as cdvsr
LEFT JOIN repeated_churn_customers as rcc
ON cdvsr.customer_id=rcc.customer_id
),
cdvsrc_top AS (
SELECT 
       cdvsrc.customer_id, cdvsrc.age, cdvsrc.mobile, cdvsrc.customer_type,
       cdvsrc.assigned_staff_id, cdvsrc.referred_by_id,
       cdvsrc.vision_type, cdvsrc.staff_full_name,
	   cdvsrc.repeated_customers,
       cdvsrc.repeated_churn_customers,
       tc.customer_id as top_50_customers
FROM cdvsr_churn as cdvsrc
LEFT JOIN top_50_customers as tc
ON tc.customer_id=cdvsrc.customer_id
),
cdvsrct_invoices AS (
SELECT 
	   cdvsrct.customer_id, cdvsrct.age, cdvsrct.mobile, cdvsrct.customer_type,
       cdvsrct.assigned_staff_id, cdvsrct.referred_by_id,
       cdvsrct.vision_type, cdvsrct.staff_full_name,
	   cdvsrct.repeated_customers,
       cdvsrct.repeated_churn_customers,
       cdvsrct.top_50_customers,
       i.invoice_id
FROM cdvsrc_top as cdvsrct 
INNER JOIN invoices as i
ON i.customer_id=cdvsrct.customer_id
),
cdvsrcti_invoice_items AS (
SELECT 
	   cdvsrcti.customer_id, cdvsrcti.age, cdvsrcti.mobile, cdvsrcti.customer_type,
       cdvsrcti.assigned_staff_id, cdvsrcti.referred_by_id,
       cdvsrcti.vision_type, cdvsrcti.staff_full_name,
	   cdvsrcti.repeated_customers,
       cdvsrcti.repeated_churn_customers,
       cdvsrcti.top_50_customers, 
       cdvsrcti.invoice_id, ii.item_id, ii.product_id, ii.brand_id, ii.product_type_id,
       ii.quantity, ii.final_product_price
FROM cdvsrct_invoices as cdvsrcti
INNER JOIN invoice_items as ii
ON ii.invoice_id=cdvsrcti.invoice_id
)
SELECT 
	pd.product_name,
    SUM(CASE WHEN cdvsrctiii.age < 20 THEN cdvsrctiii.quantity END) AS Teenage_Customers,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 20 AND 30 THEN cdvsrctiii.quantity END) AS 20s_Customer,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 31 AND 40 THEN cdvsrctiii.quantity END) AS 30s_Customer,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 41 AND 50 THEN cdvsrctiii.quantity END) AS 40s_Customer,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 51 AND 60 THEN cdvsrctiii.quantity END) AS 50s_Customer,
    SUM(CASE WHEN cdvsrctiii.age > 60 THEN cdvsrctiii.quantity END) AS Old_Age_Customers
FROM cdvsrcti_invoice_items as cdvsrctiii
INNER JOIN products as pd
ON pd.product_id=cdvsrctiii.product_id
GROUP BY pd.product_name WITH ROLLUP;


--

SELECT 
	pd.product_id, pd.product_name, 
    SUM(CASE WHEN cdvsrctiii.age < 20 THEN cdvsrctiii.quantity END) AS Teenage_Customers,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 20 AND 30 THEN cdvsrctiii.quantity END) AS 20s_Customer,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 31 AND 40 THEN cdvsrctiii.quantity END) AS 30s_Customer,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 41 AND 50 THEN cdvsrctiii.quantity END) AS 40s_Customer,
    SUM(CASE WHEN cdvsrctiii.age BETWEEN 51 AND 60 THEN cdvsrctiii.quantity END) AS 50s_Customer,
    SUM(CASE WHEN cdvsrctiii.age > 60 THEN cdvsrctiii.quantity END) AS Old_Age_Customers
FROM product_analysis_data as cdvsrctiii
INNER JOIN products as pd
ON pd.product_id=cdvsrctiii.product_id
GROUP BY pd.product_id, pd.product_name;


-- Brand 
SELECT brand_name, COUNT(brand_name)
FROM product_brand
GROUP BY brand_name
HAVING COUNT(brand_name)>1;

-- VIEW for product analysis 

CREATE VIEW Product_Analysis_data AS 
WITH customers AS (
SELECT DISTINCT customer_id
FROM customers_details 
),
customers_detail AS (
SELECT 
       c.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id
FROM customers as c
INNER JOIN customers_details as cd
ON cd.customer_id=c.customer_id
),
cd_vision AS (
SELECT 
	   cd.customer_id, cd.age, cd.mobile, cd.customer_type,
       cd.assigned_staff_id, cd.referred_by_id,
       p.vision_type
FROM customers_detail as cd
INNER JOIN prescriptions as p
ON p.customer_id=cd.customer_id
),
cdv_staff AS (
SELECT 
       cdv.customer_id, cdv.age, cdv.mobile, cdv.customer_type,
       cdv.assigned_staff_id, cdv.referred_by_id,
       cdv.vision_type, s.staff_full_name
FROM cd_vision as cdv
INNER JOIN staff as s
ON s.staff_id=cdv.assigned_staff_id
),
cdvs_repeated AS (
SELECT 
       cdvs.customer_id, cdvs.age, cdvs.mobile, cdvs.customer_type,
       cdvs.assigned_staff_id, cdvs.referred_by_id,
       cdvs.vision_type, cdvs.staff_full_name,
	   rc.customer_id as repeated_customers
FROM cdv_staff as cdvs
LEFT JOIN repeated_customers as rc
ON rc.customer_id=cdvs.customer_id
),
cdvsr_churn AS (
SELECT 
       cdvsr.customer_id, cdvsr.age, cdvsr.mobile, cdvsr.customer_type,
       cdvsr.assigned_staff_id, cdvsr.referred_by_id,
       cdvsr.vision_type, cdvsr.staff_full_name,
	   cdvsr.repeated_customers,
       rcc.customer_id as repeated_churn_customers
FROM cdvs_repeated as cdvsr
LEFT JOIN repeated_churn_customers as rcc
ON cdvsr.customer_id=rcc.customer_id
),
cdvsrc_top AS (
SELECT 
       cdvsrc.customer_id, cdvsrc.age, cdvsrc.mobile, cdvsrc.customer_type,
       cdvsrc.assigned_staff_id, cdvsrc.referred_by_id,
       cdvsrc.vision_type, cdvsrc.staff_full_name,
	   cdvsrc.repeated_customers,
       cdvsrc.repeated_churn_customers,
       tc.customer_id as top_50_customers
FROM cdvsr_churn as cdvsrc
LEFT JOIN top_50_customers as tc
ON tc.customer_id=cdvsrc.customer_id
),
cdvsrct_invoices AS (
SELECT 
	   cdvsrct.customer_id, cdvsrct.age, cdvsrct.mobile, cdvsrct.customer_type,
       cdvsrct.assigned_staff_id, cdvsrct.referred_by_id,
       cdvsrct.vision_type, cdvsrct.staff_full_name,
	   cdvsrct.repeated_customers,
       cdvsrct.repeated_churn_customers,
       cdvsrct.top_50_customers,
       i.invoice_id
FROM cdvsrc_top as cdvsrct 
INNER JOIN invoices as i
ON i.customer_id=cdvsrct.customer_id
),
cdvsrcti_invoice_items AS (
SELECT 
	   cdvsrcti.customer_id, cdvsrcti.age, cdvsrcti.mobile, cdvsrcti.customer_type,
       cdvsrcti.assigned_staff_id, cdvsrcti.referred_by_id,
       cdvsrcti.vision_type, cdvsrcti.staff_full_name,
	   cdvsrcti.repeated_customers,
       cdvsrcti.repeated_churn_customers,
       cdvsrcti.top_50_customers, 
       cdvsrcti.invoice_id, ii.item_id, ii.product_id, ii.brand_id, ii.product_type_id,
       ii.quantity, ii.final_product_price
FROM cdvsrct_invoices as cdvsrcti
INNER JOIN invoice_items as ii
ON ii.invoice_id=cdvsrcti.invoice_id
)
SELECT 
	   cdvsrctiii.customer_id, cdvsrctiii.age, cdvsrctiii.mobile, cdvsrctiii.customer_type,
       cdvsrctiii.assigned_staff_id, cdvsrctiii.referred_by_id,
       cdvsrctiii.vision_type, cdvsrctiii.staff_full_name,
	   cdvsrctiii.repeated_customers,
       cdvsrctiii.repeated_churn_customers,
       cdvsrctiii.top_50_customers, 
       cdvsrctiii.invoice_id, cdvsrctiii.item_id, 
       cdvsrctiii.product_id, cdvsrctiii.brand_id, 
       cdvsrctiii.product_type_id,
       cdvsrctiii.quantity, cdvsrctiii.final_product_price
FROM cdvsrcti_invoice_items as cdvsrctiii;

-- Top Selling Glass Brand QTY across Age group
SELECT 
      pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
	SUM(CASE WHEN pad.age < 20 THEN pad.quantity END) AS Teenage_Customers,
    SUM(CASE WHEN pad.age BETWEEN 20 AND 30 THEN pad.quantity END) AS 20s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 31 AND 40 THEN pad.quantity END) AS 30s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 41 AND 50 THEN pad.quantity END) AS 40s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 51 AND 60 THEN pad.quantity END) AS 50s_Customer,
    SUM(CASE WHEN pad.age > 60 THEN pad.quantity END) AS Old_Age_Customers
FROM product_analysis_data as pad
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
INNER JOIN products as pd
ON pd.product_id=pad.product_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name
HAVING pb.product_id=2
UNION ALL
SELECT 
      pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
	SUM(CASE WHEN pad.age < 20 THEN pad.quantity END) AS Teenage_Customers,
    SUM(CASE WHEN pad.age BETWEEN 20 AND 30 THEN pad.quantity END) AS 20s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 31 AND 40 THEN pad.quantity END) AS 30s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 41 AND 50 THEN pad.quantity END) AS 40s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 51 AND 60 THEN pad.quantity END) AS 50s_Customer,
    SUM(CASE WHEN pad.age > 60 THEN pad.quantity END) AS Old_Age_Customers
FROM product_analysis_data as pad
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
INNER JOIN products as pd
ON pd.product_id=pad.product_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name
HAVING pb.product_id=1
UNION ALL
SELECT 
      pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
	SUM(CASE WHEN pad.age < 20 THEN pad.quantity END) AS Teenage_Customers,
    SUM(CASE WHEN pad.age BETWEEN 20 AND 30 THEN pad.quantity END) AS 20s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 31 AND 40 THEN pad.quantity END) AS 30s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 41 AND 50 THEN pad.quantity END) AS 40s_Customer,
    SUM(CASE WHEN pad.age BETWEEN 51 AND 60 THEN pad.quantity END) AS 50s_Customer,
    SUM(CASE WHEN pad.age > 60 THEN pad.quantity END) AS Old_Age_Customers
FROM product_analysis_data as pad
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
INNER JOIN products as pd
ON pd.product_id=pad.product_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name
HAVING pb.product_id=3;

-- Top Selling Frame brand by revenue and QTY

SELECT 
	pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
    SUM(pad.quantity) AS QTY_SOLD,
    SUM(pad.final_product_price) AS Revenue
FROM product_analysis_data as pad
INNER JOIN products as pd
ON pd.product_id=pad.product_id
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name 
HAVING product_id=1;

-- Top Selling Glass brand by revenue and QTY
SELECT 
	pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
    SUM(pad.quantity) AS QTY_SOLD,
    SUM(pad.final_product_price) AS Revenue
FROM product_analysis_data as pad
INNER JOIN products as pd
ON pd.product_id=pad.product_id
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name 
HAVING product_id=2;

-- -- Top Selling Sunglass brand by revenue and QTY
SELECT 
	pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
    SUM(pad.quantity) AS QTY_SOLD,
    SUM(pad.final_product_price) AS Revenue
FROM product_analysis_data as pad
INNER JOIN products as pd
ON pd.product_id=pad.product_id
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name 
HAVING product_id=3;

-- Top Selling Contact Lens brand by revenue and QTY
SELECT 
	pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
    SUM(pad.quantity) AS QTY_SOLD,
    SUM(pad.final_product_price) AS Revenue
FROM product_analysis_data as pad
INNER JOIN products as pd
ON pd.product_id=pad.product_id
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name 
HAVING product_id=4;

-- Top Lens Solution brand by revenue and QTY
SELECT 
	pb.product_id, pd.product_name, pb.brand_id, pb.brand_name,
    SUM(pad.quantity) AS QTY_SOLD,
    SUM(pad.final_product_price) AS Revenue
FROM product_analysis_data as pad
INNER JOIN products as pd
ON pd.product_id=pad.product_id
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
GROUP BY pb.product_id, pd.product_name, pb.brand_id, pb.brand_name 
HAVING product_id=6;

-- 
SELECT 
      pd.product_id, pd.product_name, pb.brand_id, pb.brand_name,
      SUM( CASE WHEN pad.age<20 THEN pad.quantity END) AS Teenage_Customers,
      SUM( CASE WHEN pad.age BETWEEN 21 AND 30 THEN pad.quantity END) AS 20s_Customers,
      SUM( CASE WHEN pad.age BETWEEN 31 AND 40 THEN pad.quantity END) AS 20s_Customers,
      SUM( CASE WHEN pad.age BETWEEN 41 AND 50 THEN pad.quantity END) AS 20s_Customers,
      SUM( CASE WHEN pad.age BETWEEN 51 AND 60 THEN pad.quantity END) AS 20s_Customers,
      SUM( CASE WHEN pad.age>61 THEN pad.quantity END) AS Old_Age_Customers
FROM product_analysis_data as pad
INNER JOIN product_brand as pb
ON pb.brand_id=pad.brand_id
INNER JOIN products as pd
ON pd.product_id=pad.product_id
GROUP BY pd.product_id, pd.product_name, pb.brand_id, pb.brand_name;



-- ====================== END OF Product & Brand Analysis ====================== ---