
-- 2.5) Top 50 Customers

-- 2.5.1) Top 50 Customers Based on the Total revenue generated by them

CREATE VIEW top_50_customers AS 
SELECT i.customer_id, SUM(i.final_bill_amount) AS Total_Revenue_by_Customer
FROM invoices as i
GROUP BY i.customer_id
ORDER BY Total_Revenue_by_Customer DESC
LIMIT 50;

-- verifying the Query (to check whether the values are inflated or not)
SELECT i.customer_id, i.final_bill_amount FROM invoices as i
WHERE i.customer_id=5669;

-- 2.5.2) Top 50 Customers Based on the Revenue V/S Vision_Type 
SELECT p.vision_type, COUNT(tc.customer_id) AS Count_Customers
FROM top_50_customers as tc
INNER JOIN prescriptions as p
ON tc.customer_id=p.customer_id
GROUP BY p.vision_type
ORDER BY Count_Customers DESC;

-- 2.5.3) Top Selling Products Among the Top 50 Customers
SELECT p.product_name, COUNT(ii.item_id) AS total_units_sold
FROM top_50_customers as v

JOIN invoices i 
ON v.customer_id = i.customer_id
JOIN invoice_items ii 
ON i.invoice_id = ii.invoice_id
JOIN products p 
ON ii.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_units_sold DESC;

-- 2.5.4) Age_group of TOP 50 Customers
SELECT
CASE 
    WHEN age < 20 THEN "Teenage_Customer"
    WHEN age BETWEEN 20 AND 30 THEN "20's Customer"
    WHEN age BETWEEN 31 AND 40 THEN "30's Customer"
    WHEN age BETWEEN 41 AND 50 THEN "40's Customer"
    WHEN age BETWEEN 51 AND 60 THEN "50's Customer"
    WHEN age > 60 THEN "Old_Age Customers"
  END AS Age_group,
  COUNT(DISTINCT tc.customer_id) AS COUNT_customers
FROM customers_details as c
INNER JOIN top_50_customers as tc
ON tc.customer_id=c.customer_id
GROUP BY Age_group
ORDER BY COUNT_customers DESC;

-- 2.5.5) Customer Type of TOP 50 Customers
SELECT c.customer_type, COUNT(tc.customer_id) AS COUNT_Customers
FROM customers_details as c
INNER JOIN top_50_customers as tc
ON c.customer_id=tc.customer_id
GROUP BY c.customer_type 
ORDER BY COUNT_Customers DESC;

-- 2.5.6) Top 50 Customers V/S Months
SELECT MONTH(i.invoice_date) AS Month , YEAR(i.invoice_date) AS Year, COUNT(DISTINCT tc.customer_id) AS COUNT_Customers
FROM customers_details as c
INNER JOIN top_50_customers as tc
ON tc.customer_id=c.customer_id
INNER JOIN invoices as i
ON i.customer_id=tc.customer_id
GROUP BY MONTH(i.invoice_date), YEAR(i.invoice_date)
ORDER BY Year, Month;

-- 2.5.7) At-Risk VIPs (Haven't shopped in over 180 days)
SELECT 
    tc.customer_id, 
    c.customer_full_name, 
    c.mobile,
    MAX(i.invoice_date) AS last_purchase_date,
    DATEDIFF('2026-02-02', MAX(i.invoice_date)) AS days_since_last_visit
FROM top_50_customers tc
JOIN customers_details c 
ON tc.customer_id = c.customer_id
JOIN invoices i 
ON tc.customer_id = i.customer_id
GROUP BY tc.customer_id, c.customer_full_name, c.mobile
HAVING days_since_last_visit > 180
ORDER BY days_since_last_visit DESC;
