-- =========================================================
-- ========= 2.6) Referrers Analysis ============== 
-- =========================================================

-- 2.6.1) Extracted the Referrers
SELECT DISTINCT c.referred_by_id FROM customers_details as c
WHERE c.referred_by_id IS NOT NULL;

-- 2.6.2) COUNT of Referrers = 721 Referrers are their in our dataset;
-- out of 721 some are our buyers and interestingly there are Non_buyers too who gave our referral
SELECT COUNT(DISTINCT c.referred_by_id) AS COUNT_Referring_Person FROM customers_details as c
WHERE c.referred_by_id IS NOT NULL;

-- 2.6.3) Number of referrals given by each Referrer = 
SELECT 
      c.referred_by_id, 
	 COUNT(DISTINCT c.customer_id) AS Number_of_Referrals
FROM customers_details as c
GROUP BY c.referred_by_id 
HAVING c.referred_by_id IS NOT NULL 
ORDER BY Number_of_Referrals DESC;

-- 2.6.4) COUNT of Customers Visited by referrals = 810 Customers 
-- Out of 8000 Visited Customers 7190 Customers are Non-referral Customers
-- It means 8000-7190 = 810 Customers are our referrals Customers
-- Out of 8000 Visited Customers 810 Customers are our Referral Customers
SELECT c.referred_by_id, c.customer_id
FROM customers_details as c
WHERE c.referred_by_id IS NOT NULL;

-- COUNT 
SELECT 
      COUNT(DISTINCT c.customer_id) AS COUNT_of_Referral_customer
FROM customers_details as c
WHERE c.referred_by_id IS NOT NULL;

-- 2.6.5) Out of 8000 Visited Customers 7190 Customers are Non-referral Customers
-- It means 8000-7190 = 810 Customers are our referrals Customers
-- Out of 8000 Visited Customers 810 Customers are our Referral Customers

-- Count of Non_Referral_Customers
-- Out of 8000 Visited Customers 7190 Customers are Non_Referral_Customers 


-- Non referral_Customers = 7190 Customers
SELECT 
      c.referred_by_id, 
      COUNT(DISTINCT c.customer_id) AS Number_of_Referrals
FROM customers_details as c
GROUP BY c.referred_by_id
HAVING  c.referred_by_id IS NULL;

-- 2.6.5.2) Only 10.13 % of Customers are referrals out of all the Visited Customers
WITH referred_customers_with_referral AS (
SELECT c.referred_by_id, c.customer_id
FROM customers_details as c
WHERE c.referred_by_id IS NOT NULL
) 
SELECT COUNT(DISTINCT c.customer_id) AS Total_Visited_Customers,
       ROUND( COUNT(DISTINCT c.customer_id) - COUNT(DISTINCT rcwr.customer_id), 2 ) AS COUNT_Non_Referral_Customers,
       COUNT(DISTINCT rcwr.customer_id) AS Count_of_Referral_Customers,
       ROUND( COUNT(DISTINCT rcwr.customer_id) * 100 / COUNT(DISTINCT c.customer_id), 2) AS Percentage_of_Referral_Customers
FROM customers_details as c
LEFT JOIN referred_customers_with_referral as rcwr 
ON c.customer_id=rcwr.customer_id;


-- 2.6.6) Total Revenue Generated by referral customer
SELECT c.referred_by_id, c.customer_id, i.final_bill_amount
FROM customers_details as c
INNER JOIN invoices as i
ON c.customer_id=i.customer_id
WHERE c.referred_by_id IS NOT NULL;

-- Total Revenue Generated by referral customer = 47,63,973.00
-- 47lakhs 63Thousand is the Total Revenue Generated from the Referral Customers
SELECT SUM(i.final_bill_amount) AS Revenue_Generated_from_referral_Customers
FROM customers_details as c
INNER JOIN invoices as i
ON c.customer_id=i.customer_id
WHERE c.referred_by_id IS NOT NULL;

-- 2.6.6.1) Percentage Contribution of revenue generated by Referrals in the Total_Revenue
-- Revenue Generated by the Referral Customers contributes 10.18% to the Total_Revenue
SELECT 
    SUM(i.final_bill_amount) AS Total_Revenue,
    SUM(CASE WHEN c.referred_by_id IS NOT NULL THEN i.final_bill_amount ELSE 0 END) AS Referral_Revenue,
    ROUND(SUM(CASE WHEN c.referred_by_id IS NOT NULL THEN i.final_bill_amount ELSE 0 END) * 100 / SUM(i.final_bill_amount), 2) AS Referral_Contribution_Pct
FROM customers_details AS c
INNER JOIN invoices AS i 
ON c.customer_id = i.customer_id;

-- 2.6.7) COUNT of Referral Customers
-- Out of 810 Customers 381 has become our buyers
SELECT 
      COUNT(DISTINCT i.customer_id) AS Referral_Buyers
FROM customers_details as c
INNER JOIN invoices as i
ON c.customer_id=i.customer_id
WHERE c.referred_by_id IS NOT NULL;

-- 2.6.8) Top Referrers (Who has given more than 2 Referrals)
SELECT c.referred_by_id, COUNT(c.customer_id) AS Number_of_Referrals
FROM customers_details as c
GROUP BY c.referred_by_id 
HAVING Number_of_Referrals > 2
ORDER BY Number_of_Referrals DESC;

-- 2.6.9) Final Summary of Referers, Referral_buyers and Comparison of their Revenue and Percentage 
SELECT 
      SUM(i.final_bill_amount) AS Total_Revenue_Generated,
      SUM(CASE WHEN c.referred_by_id IS NULL THEN i.final_bill_amount ELSE 0 END) AS Revenue_Genertaed_by_Non_Referrals,
      SUM(CASE WHEN c.referred_by_id IS NOT NULL THEN i.final_bill_amount ELSE 0 END) AS Revenue_Generated_by_Referrals,
      ROUND( SUM(CASE WHEN c.referred_by_id IS NOT NULL THEN i.final_bill_amount ELSE 0 END) * 100 / SUM(i.final_bill_amount), 2) 
      AS Percentage_Contribution_of_Referrals_in_Revenue
FROM customers_details as c
INNER JOIN invoices as i
ON c.customer_id=i.customer_id;

-- 2.6.10) Referrer_Age_group 
-- Highest Referrals are from Old_Age-Customer(That is customers age greater than 59)  

WITH referrers AS (
SELECT
      c.referred_by_id
FROM customers_details as c
GROUP BY c.referred_by_id      
)
SELECT
CASE 
    WHEN c.age < 20 THEN "Teenage_Customer"
    WHEN c.age BETWEEN 20 AND 30 THEN "20's Customer"
    WHEN c.age BETWEEN 31 AND 40 THEN "30's Customer"
    WHEN c.age BETWEEN 41 AND 50 THEN "40's Customer"
    WHEN c.age BETWEEN 51 AND 60 THEN "50's Customer"
    WHEN c.age > 60 THEN "Old_Age Customers (age>60)"
  END AS Referrer_Age_group,
COUNT(DISTINCT referrers.referred_by_id ) AS COUNT_Referrals
FROM customers_details as c  
INNER JOIN referrers
ON referrers.referred_by_id=c.customer_id
GROUP BY Referrer_Age_group 
ORDER BY COUNT_Referrals DESC;
-- OR --
SELECT 
CASE 
    WHEN c.age < 20 THEN "Teenage_Customer"
    WHEN c.age BETWEEN 20 AND 30 THEN "20's Customer"
    WHEN c.age BETWEEN 31 AND 40 THEN "30's Customer"
    WHEN c.age BETWEEN 41 AND 50 THEN "40's Customer"
    WHEN c.age BETWEEN 51 AND 60 THEN "50's Customer"
    WHEN c.age > 60 THEN "Old_Age Customers (age>60)"
  END AS Referrer_Age_group,
COUNT(DISTINCT referrers.referred_by_id) AS COUNT_Unique_Referrers
FROM customers_details as c
INNER JOIN customers_details as referrers
ON referrers.referred_by_id=c.customer_id
GROUP BY Referrer_Age_group WITH ROLLUP
ORDER BY COUNT_Unique_Referrers DESC;

-- Old_Age Customers are out Highest Referrals
