-- ======================================================
-- ===========  Non_Buyers_Referrers_Analysis  ==============
-- ======================================================

-- 2.6.4.2) Audit Query 
-- Out of 721 Referrers how many Referrers actually is our customers / Buyers and their conversion rate
-- I observe one thing; that is, only 333 referring persons are our buyers out of 721 Total referrals 
-- The Thing is Notable because this is very abnormal thing ( how can someone who is not our buyer/customer can referrer us?)

-- 2.6.4.2.1) 
-- This Query get us the Referrers who are our Buyers / Customers
SELECT c.referred_by_id, i.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id;

-- This Query Gives us the Count of Referrers who are our Buyers / Customers
-- Only 333 Referring People are our Customers/Buyers out of 721; rest 388 are not our customers / buyers
SELECT 
	  COUNT(DISTINCT i.customer_id) AS COUNT_Buyer_Referrers
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id;

-- This QUery will get you the referrers who are not buyers /customers
-- -- That is 388 Referrers out of 721 are not even our Buyers / Customers
SELECT c.referred_by_id, i.customer_id
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL;

-- Follow Up Query to COUNT the Non_Buyer_Referrers

SELECT COUNT(DISTINCT c.referred_by_id) AS COUNT_Non_Buyers_Referrers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL;

-- Summary of Referrers who are Buyers V/S ; and their Conversion Rate
SELECT 
      COUNT(DISTINCT c.referred_by_id) AS Total_Referrers,
      COUNT(DISTINCT CASE WHEN c.referred_by_id IS NOT NULL AND i.customer_id IS NOT NULL THEN c.referred_by_id END) AS COUNT__Buyers_Referrer, 
      COUNT(DISTINCT CASE WHEN c.referred_by_id IS NOT NULL AND i.customer_id IS NULL THEN c.referred_by_id END) AS COUNT_NON_Buyers_Referrer,
      ROUND( COUNT(DISTINCT CASE WHEN c.referred_by_id IS NOT NULL AND i.customer_id IS NOT NULL THEN c.referred_by_id END) * 100 / COUNT(DISTINCT c.referred_by_id), 2) AS Referrers_Conversion_Rate
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id;

-- Revenue Generated BY Non_Buyers_Referrers 
-- 
WITH non_buyer_referrers AS (
SELECT c.referred_by_id, c.customer_id
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
)
SELECT 
      SUM(i.final_bill_amount)
FROM non_buyer_referrers as nbr
INNER JOIN invoices as i
ON nbr.customer_id=i.customer_id;



-- Repeated Customers in Buyers_Referrers
SELECT c.referred_by_id, i.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id;

-- Deep Analysis of Non_Buyers_Referrers ---> Lets Call them as as Ghost_Referrers
-- 2.6.4.2.3) Checking how many overall referrals given by the Non-Buyers-referres
-- Total 436 Referrals has being given by the Non-Buyers-referrers

SELECT c.referred_by_id, c.customer_id, i.customer_id
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL;

-- Total 436 Referrals has being given by the Non-Buyers-referrers
SELECT 
      COUNT(DISTINCT c.customer_id) AS Total_Unique_Referrals
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL;

-- 2.6.5) "Do these non-buyer referrals actually result in sales, or are they low-quality leads?"
-- DEEP Analysis of Buyers from Non_Buyer_Referrers
-- Checking whether non-buyers referrers, referred customers has generated sales or not 

WITH non_buyers_referrers AS (
SELECT 
      c.referred_by_id, 
	  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
) 
SELECT i.customer_id, i.invoice_id 
FROM invoices as i
INNER JOIN non_buyers_referrers as nbr
ON nbr.referral_customers=i.customer_id;

-- 2.6.5.1) COUNT of customers referred by the non buyers referrers
-- Out of the 388 Non-Buyers Referrers they have given a total of 436 referrals out of which-
-- 213 Refferals has become a buyers
WITH non_buyers_referrers AS (
SELECT 
      c.referred_by_id, 
	  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
) 
SELECT 
      COUNT(i.customer_id) AS Total_Customers,
      COUNT(DISTINCT i.customer_id) AS Unique_Buyer_from_non_buyers_referrers,
      ROUND( COUNT(i.customer_id) - COUNT(DISTINCT i.customer_id), 2) AS Total_Repeated_Customers_By_Non_Referrers_Buyers
FROM invoices as i
INNER JOIN non_buyers_referrers as nbr
ON nbr.referral_customers=i.customer_id;
-- Here the diferrernce between the Unique Customers and DISTINCT Customers is diferrent
-- hence the referral customers by the non_buyers referrers are also the part of the repeating customers (thats a really best thing)
 
-- Extracting the Repeated Customers of referrals bf Non_Buyers_Referrers 
WITH non_buyers_referrers AS (
SELECT 
      c.referred_by_id, 
	  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
)
SELECT 
     i.customer_id, COUNT(i.customer_id) AS Number_of_Times_Repeated_referrals_of_Non_Buyers_Referrers
FROM invoices as i
INNER JOIN non_buyers_referrers as nbr
ON nbr.referral_customers=i.customer_id
GROUP BY i.customer_id
HAVING Number_of_Times_Repeated_referrals_of_Non_Buyers_Referrers > 1
ORDER BY Number_of_Times_Repeated_referrals_of_Non_Buyers_Referrers DESC;

-- COUNT Repeated Customers of referrals by Non_Buyers_Referrers 
WITH non_buyers_referrers AS (
SELECT 
      c.referred_by_id, 
	  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
),
Repeated_Customers_of_referrals_of_Non_Buyers_Referrers AS (
SELECT 
     i.customer_id, COUNT(i.customer_id) AS Number_of_Times_Repeated_referrals_of_Non_Buyers_Referrers
FROM invoices as i
INNER JOIN non_buyers_referrers as nbr
ON nbr.referral_customers=i.customer_id
GROUP BY i.customer_id
HAVING Number_of_Times_Repeated_referrals_of_Non_Buyers_Referrers > 1
ORDER BY Number_of_Times_Repeated_referrals_of_Non_Buyers_Referrers DESC
)
SELECT COUNT(Repeated_Customers_of_referrals_of_Non_Buyers_Referrers.customer_id)
FROM Repeated_Customers_of_referrals_of_Non_Buyers_Referrers;

-- Revenue Generated from the buyers of Non_Buyers_Referrers
-- 2653041.00 That is around 26 Lakhs 53 Thousand
-- It means Non_Buyers Referral has also helped us in generating the Sales

-- Revenue Generated from Non_Buyer_referrals -- Result : 2653041.00
WITH non_buyers_referrers AS (
SELECT 
      DISTINCT c.referred_by_id, 
  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
)
SELECT 
     SUM(i.final_bill_amount) AS Revenue_Generated_from_the_buyers_of_Non_Buyers_Referrers
FROM invoices as i
INNER JOIN non_buyers_referrers as nbr
ON nbr.referral_customers=i.customer_id;

-- DEEP Analysis of Non_Buyers FROm the NON_Buyers_Referrers

-- Out of 436 Referrals from Non_Buyers_Referrers; 223 are Non Buyers

WITH non_buyers_referrers AS (
SELECT 
      c.referred_by_id, 
	  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
) 
SELECT nbr.referral_customers, i.customer_id 
FROM non_buyers_referrers as nbr
LEFT JOIN invoices as i
ON nbr.referral_customers=i.customer_id
WHERE i.customer_id IS NULL;

-- COUNT of Non_buyers from Non_buyers_referrers
-- Out of 436 Referrals from Non_Buyers_Referrers; 
-- 223 are Non Buyers & 213 Buyers

-- Final Summary of Buyers from Non_Referrer_Buyers
WITH non_buyers_referrers AS (
SELECT 
      c.referred_by_id, 
	  c.customer_id AS referral_customers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id
WHERE i.customer_id IS NULL AND c.referred_by_id IS NOT NULL
) 
SELECT
      SUM(i.final_bill_amount) AS Revenue_Generated_from_Non_buyers_referrers,
      COUNT(DISTINCT referral_customers) AS Total_referral_from_Non_referrer_buyers,
      COUNT(DISTINCT CASE WHEN i.customer_id IS NULL THEN nbr.referral_customers END) AS Non_Buyers_from_Non_Buyers_Referrers,
      COUNT(DISTINCT CASE WHEN i.customer_id IS NOT NULL THEN nbr.referral_customers END) AS Buyers_from_Non_Buyers_Referrers,
-- Calculating the Conversion Rate of Referrals from Non       
      ROUND(COUNT(DISTINCT CASE WHEN i.customer_id IS NOT NULL THEN nbr.referral_customers END) * 100 / COUNT(DISTINCT referral_customers), 2) AS Conversion_Rate_of_referral_from_Non_buyer_Referrers
FROM non_buyers_referrers as nbr
LEFT JOIN invoices as i
ON nbr.referral_customers=i.customer_id;
