-- ===============================================================
-- ============ 2.6) 3) Analysis on Buyer_Referrers===============
-- ===============================================================

-- 1) Extracting the Referrer Buyers 
SELECT DISTINCT c.referred_by_id
FROM customers_details as c
INNER JOIN invoices as i
On c.referred_by_id=i.customer_id;

-- COUNT of Referrers Buyers 
-- Out of 721 referrers; 333 referrers are our Uniuqe buyers 
WITH referrer_buyers AS (
SELECT DISTINCT c.referred_by_id
FROM customers_details as c
INNER JOIN invoices as i
On c.referred_by_id=i.customer_id
)
SELECT COUNT(*) AS COUNT_Unique_Buyers
FROM referrer_buyers;

-- Lets Check COUNT the Repeated Buyer_Referrers 
-- Out of 333 buyer_referrer 97 referrer are our repeated_customers
WITH unique_referrer_buyers AS (
SELECT DISTINCT c.referred_by_id 
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
),
unique_repeated__buyer_referrer AS (
SELECT urb.referred_by_id, COUNT(i.customer_id) AS Number_of_times_Buyer_referrers_repeated
FROM unique_referrer_buyers AS urb
INNER JOIN invoices as i
On urb.referred_by_id=i.customer_id
GROUP BY urb.referred_by_id 
HAVING COUNT(i.customer_id) > 1
ORDER BY COUNT(i.customer_id) DESC
)
SELECT COUNT(*) AS Total_Repeated_Buyer_Referrers
FROM unique_repeated__buyer_referrer;

-- Here are those repeated buyer_referrer and their count of how many times they are repeated
-- Lets Check COUNT the Repeated Buyer_Referrers 
-- Out of 333 buyer_referrer 97 referrer are our repeated_customers
WITH unique_referrer_buyers AS (
SELECT DISTINCT c.referred_by_id 
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
)
SELECT urb.referred_by_id, COUNT(i.customer_id) AS Number_of_times_Buyer_referrers_repeated
FROM unique_referrer_buyers AS urb
INNER JOIN invoices as i
On urb.referred_by_id=i.customer_id
GROUP BY urb.referred_by_id 
HAVING COUNT(i.customer_id) > 1
ORDER BY COUNT(i.customer_id) DESC;

-- Total Revenue Collected From Buyer_referrer  (Note this the revenue we have collected from the buyer_referrer when they made a purchase; and not the the revenue collected from their referrrals) 
-- Hence the total revenue collected from this buyer_referrer is 4304354.00
WITH unique_buyer_referrer AS (
SELECT DISTINCT c.referred_by_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
)
SELECT SUM(i.final_bill_amount)
FROM unique_buyer_referrer as ubr
INNER JOIN invoices as i
ON ubr.referred_by_id=i.customer_id;

-- Percentage Calculation of referrers who are our buyers out of all the referrers

SELECT c.referred_by_id, c.customer_id, i.customer_id
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id;

-- Percentage Calculation of Buyer_Referrers      
-- 46.19% of referrers out of 721 referrers are buyer_referrers 
SELECT 
      COUNT(DISTINCT c.referred_by_id) AS Total_COUNT_of_Referrers,
      COUNT(DISTINCT  CASE WHEN i.customer_id IS NOT NULL AND c.referred_by_id IS NOT NULL THEN c.referred_by_id END) AS COUNT_Buyer_Referrers,
      COUNT(DISTINCT CASE WHEN i.customer_id IS NULL AND c.referred_by_id IS NOT NULL THEN c.referred_by_id END) AS COUNT_Non_Buyer_Referrers,
-- Percentage Calculation of Buyer_Referrers      
      ROUND( COUNT(DISTINCT  CASE WHEN i.customer_id IS NOT NULL AND c.referred_by_id IS NOT NULL THEN c.referred_by_id END) * 100 / 
      COUNT(DISTINCT c.referred_by_id), 2) AS Percentage_of_Referrer_Buyers
FROM customers_details as c
LEFT JOIN invoices as i
ON c.referred_by_id=i.customer_id;

-- Revenue Generated by Buyer referrers referrals
-- -- Result : 2110932.00

WITH buyer_referrers AS (
SELECT DISTINCT c.referred_by_id, c.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
)
SELECT SUM(i.final_bill_amount)
FROM invoices as i
INNER JOIN buyer_referrers as br
ON br.customer_id=i.customer_id;

-- COUNT of referrals given by the buyer_referrers
-- That as total pf 374 referrals are given by the buyer_referrer
WITH buyer_referrer AS (
SELECT c.referred_by_id, c.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
)
SELECT COUNT(DISTINCT br.customer_id) AS COUNT_Referrals_by_Buyer_referrers
FROM buyer_referrer as br;

-- Count of buyer_referrals given by the Buyer referrer
-- 168 referral are buyers out of all the referrals 
WITH buyer_referrer AS (
SELECT c.referred_by_id, c.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
)
SELECT COUNT(DISTINCT br.customer_id) AS COUNT_Referral_Buyers
FROM buyer_referrer as br
INNER JOIN invoices as i
ON br.customer_id=i.customer_id;

-- Final Summary about the buyer_referrers
-- COUNT of referrals from referrer buyers, segregating them on the basis of buyer referral and non_buyer referral
-- Total 374 Referrals
-- 168 are buyers
-- 206 are Non_Buyers
-- 44.92 is the Conversion_Rate of the referrals to buyers
WITH buyer_referrer AS (
SELECT c.referred_by_id, c.customer_id
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
)
SELECT 
      COUNT(DISTINCT br.customer_id) AS Total_Referrals_from_Buyer_referrers,
      COUNT(DISTINCT CASE WHEN i.customer_id IS NOT NULL THEN br.customer_id END) AS COUNT_Buyer_referrals_from_buyer_referrers,
      COUNT(DISTINCT CASE WHEN i.customer_id IS NULL THEN br.customer_id END) AS COUNT_Non_buyers_from_buyer_referrers,
-- calculating the conversion rate 
      ROUND(  COUNT(DISTINCT CASE WHEN i.customer_id IS NOT NULL THEN br.customer_id END) * 100 /  COUNT(DISTINCT br.customer_id), 2) AS Conversion_Rate_to_buyers,
      COUNT(DISTINCT CASE WHEN i.customer_id IS NULL THEN br.customer_id END) AS COUNT_Non_Buyer_referrals_from_buyer_referrers
FROM buyer_referrer as br
LEFT JOIN invoices as i
ON br.customer_id=i.customer_id;

-- Buyer Referrer Age group
-- So our Highest referrer are from the Old_Age_Groups
WITH unique_referrer_buyer AS (
SELECT DISTINCT c.referred_by_id 
FROM customers_details as c
INNER JOIN invoices as i
ON c.referred_by_id=i.customer_id
),
unique_referrer_buyer_age AS (
SELECT urb.referred_by_id, c.age
FROM unique_referrer_buyer as urb
INNER JOIN customers_details as c
ON urb.referred_by_id=c.customer_id
)
SELECT
CASE 
    WHEN urba.age < 20 THEN "Teenage_Customer"
    WHEN urba.age BETWEEN 20 AND 30 THEN "20's Customer"
    WHEN urba.age BETWEEN 31 AND 40 THEN "30's Customer"
    WHEN urba.age BETWEEN 41 AND 50 THEN "40's Customer"
    WHEN urba.age BETWEEN 51 AND 60 THEN "50's Customer"
    WHEN urba.age > 60 THEN "Old_Age Customers"
  END AS Age_group,
COUNT(DISTINCT urba.referred_by_id) AS COUNT_Referrer_Buyer
FROM unique_referrer_buyer_age as urba
GROUP BY Age_group WITH ROLLUP
ORDER BY COUNT_Referrer_Buyer DESC;